language: php

services:
  - mysql

before_script:
  - cp hudson/*.yml config/
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - sudo apt-get install -y xpdf ffmpeg libavcodec-extra-53 openoffice.org-writer unoconv ghostscript gsfonts dcraw ufraw graphicsmagick libgraphicsmagick1-dev libfreetype6-dev libjpeg-dev libgif-dev libtiff-dev libdjvulibre-dev libwmf-dev libmagickcore-dev libmagickwand-dev libpng-dev gettext zlib1g-dev build-essential libfaac-dev libmp3lame0 libx264-dev libvpx-dev libtheora-dev libvorbis-dev gpac
  - sudo apt-get autoremove
  - sudo apt-get clean
  - mysql -e 'create database ab_test;create database db_test; create database ab_unitTests; create database db_unitTests;'
  - sudo mysql -e "GRANT ALL PRIVILEGES ON ab_unitTests.* TO 'phraseaUnitTests'@'localhost' IDENTIFIED BY 'iWvGxPE8' WITH GRANT OPTION"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON db_unitTests.* TO 'phraseaUnitTests'@'localhost' IDENTIFIED BY 'iWvGxPE8' WITH GRANT OPTION"
  - mysql -e "source `pwd`/hudson/fixtures.sql"
  - mysql -e 'SET GLOBAL time_zone = "+02:00";'
  - mysql -e 'SET @@global.sql_mode= "";'
  - mysql -e 'SET @@global.wait_timeout= 999999;'
  - git clone git://github.com/alchemy-fr/Phraseanet-Extension.git
  - sh -c "cd Phraseanet-Extension && ./configure && make && sudo make install"
  - echo "extension=phrasea2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - wget http://pecl.php.net/get/gmagick-1.1.0RC2.tgz
  - tar -xzf gmagick-1.1.0RC2.tgz
  - sh -c "cd gmagick-1.1.0RC2 && phpize && ./configure --with-gmagick=/usr/local && make && sudo make install"
  - echo "extension=gmagick.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

notifications:
  irc:
    channels:
      - "irc.freenode.org#phrasea"
    template:
      - "%{repository_url} %{branch} by %{author} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
    use_notice: true

php:
  - 5.3
  - 5.4
