#Here's the main configuration file which is loaded when phraseanet bootstraps

#Declare which environment will be used by the application

environment : prod
key : null

#Declare all your environment configurations

#################
# DEVELOPPEMENT #
#################
dev:
  #Phraseanet refers to phraseanet app specific configuration
  phraseanet:
    servername: 'http://sub.domain.tld/'
    maintenance: false
    debug: true
    display_errors: true

    #Assign your phraseanet application connection
    #Connections are defined in connexions.yml configuration file
    database: main_connexion

  #Assign your template engine service & ORM service
  #Services are defined in service.yml configuration file
  template_engine: twig_debug
  orm: doctrine_dev
  cache: array_cache
  opcodecache: array_cache
  border-manager: border_manager
  search-engine: phrasea
  task-manager: config_taskmanager

##############
# PRODUCTION #
##############
prod:
  phraseanet:
    servername: 'http://sub.domain.tld/'
    maintenance: false
    debug: false
    display_errors: false
    database: main_connexion

  template_engine: twig
  orm: doctrine_prod
  cache: array_cache
  opcodecache: array_cache
  border-manager: border_manager
  search-engine: phrasea
  task-manager: config_taskmanager

##############
#    TEST    #
##############
test:
  phraseanet:
    servername: 'http://sub.domain.tld/'
    maintenance: false
    debug: true
    display_errors: true
    database: main_connexion

  template_engine: twig_debug
  orm: doctrine_test
  cache: array_cache
  opcodecache: array_cache
  border-manager: border_manager
  search-engine: phrasea
  task-manager: config_taskmanager

