showDatabases:
    path: /databases
    controller: App\Controller\DefaultController::index

test:
    path: /test
    controller: App\Controller\DefaultController::test

showUsers:
    path: /users
    controller: App\Controller\DefaultController::showUsers

showSbas:
    path: /sbas
    controller: App\Controller\DefaultController::showSbas

deleteUser:
    path: /user/delete/{id}
    controller: App\Controller\DefaultController::deleteUser

setup:
    path: /
    controller: App\Controller\SetupController::rootInstaller

install_step2:
    path: /installer/step2
    controller: App\Controller\SetupController::getInstallForm

install_do_install:
    path: /installer/install
    controller: App\Controller\SetupController::doInstall

install_root:
    path: /installer
    controller: App\Controller\SetupController::rootInstaller

admin:
    path: /admin
    controller: App\Controller\Admin\RootController::indexAction

login:
    path: /login
    controller: App\Controller\Root\LoginController::login