---
- stat: path=/etc/php/5.6/apache2/php.ini
  register: modphp

- stat: path=/etc/php/5.6/fpm/php.ini
  register: phpfpm

- stat: path=/etc/php/5.6/cli/php.ini
  register: phpcli

- include: php-fpm.yml
  when: phpfpm.stat.exists

- include: php-cli.yml
  when: phpcli.stat.exists

- include: mod-php.yml
  when: modphp.stat.exists

