{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if (index $.Values $appName).enabled }}
{{- with (index $.Values $appName) }}
{{- $tplArgs := dict "app" $appName "ctx" . "glob" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phraseanet-services
      tier: {{ $appName }}-worker
  template:
    metadata:
      labels:
        app: phraseanet-services
        tier: {{ $appName }}-worker
    spec:
      volumes:
{{- include "volumes.configs" $ | indent 6 }}
{{- include "app.volumes" $tplArgs | indent 6 }}
      containers:
      - name: {{ $appName }}-worker
        image: {{ $.Values.repository.baseurl }}/ps-{{ $appName }}-worker:{{ $.Values.repository.tag }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: configs
          mountPath: /configs
{{- include "app.volumesMounts" $tplArgs | indent 8 }}
        env:
{{ include "envRef.phpApp" $tplArgs | indent 8 }}
        envFrom:
{{ include "configMapRef.phpApp" $tplArgs | indent 8 }}
{{- include "envFrom.rabbitmq" $ | indent 8 }}
{{- include "envFrom.postgresql" $ | indent 8 }}
        - secretRef:
            name: {{ .adminOAuthClient.externalSecretName | default (printf "%s-admin-oauth-client-secret" $appName) }}
        - configMapRef:
            name: {{ $appName }}-api-config
---
{{- end }}
{{- end }}
{{- end }}
