apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phraseanet-services
      tier: uploader-client
  template:
    metadata:
      labels:
        app: phraseanet-services
        tier: uploader-client
    spec:
      volumes:
{{- include "volumes.configs" $ | indent 8 }}
      containers:
      - name: uploader-client
        image: {{ $.Values.repository.baseurl }}/ps-uploader-client:{{ $.Values.repository.tag }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: configs
          mountPath: /configs
        env:
        - name: DEV_MODE
          value: "false"
        envFrom:
        - configMapRef:
            name: urls-config
        - secretRef:
            name: {{ $.Values.uploader.client.oauthClient.externalSecretName | default "uploader-oauth-client-secret" }}
